# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    build: ./postgres
    container_name: "my_postgres"
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: l2eyxb217VSOloy
      POSTGRES_DB: socialDB
    ports:
    - 5433:5432

  adminer:
    build: ./adminer
    restart: always
    ports:
    - 6080:8080